---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - tmux
        - reflector
        - neofetch
        - neovim
        - leafpad
        - python3-psutils
